# Generated by Django 3.1.1 on 2020-09-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
