# Generated by Django 3.1.1 on 2020-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200908_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
