# Generated by Django 3.1.1 on 2020-09-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='type',
            new_name='type_of_complain',
        ),
        migrations.AddField(
            model_name='leave',
            name='address_to_go',
            field=models.TextField(default='home address'),
        ),
    ]
