# Generated by Django 3.1.1 on 2020-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200907_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='applicant',
        ),
        migrations.AddField(
            model_name='leave',
            name='applicant_name',
            field=models.TextField(default='name'),
        ),
        migrations.AddField(
            model_name='leave',
            name='applicant_phn',
            field=models.TextField(default='phone number'),
        ),
        migrations.AddField(
            model_name='leave',
            name='applicant_roll_no',
            field=models.TextField(default='roll_number'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='address_to_go',
            field=models.TextField(),
        ),
    ]
