# Generated by Django 3.1.1 on 2020-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200907_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='address_to_go',
            field=models.TextField(default='home address'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(default='no reason'),
        ),
    ]
