# Generated by Django 3.1.1 on 2020-09-08 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200908_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ph_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Phone number must be of 10 digits only consisting of number form 0-9.')]),
        ),
    ]
